import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Todo } from "../utils/types"
import Link from "next/link"

interface IndexProps {
  todos: Array<Todo>
}

const Home = (props: IndexProps) => {
  const { todos } = props

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>My Todo List</h1>
        <h2>Click On Todo to see it individually</h2>
        <Link href="/todos/create" passHref><button>Create a New Todo</button></Link>
        
        {todos.map((todo: Todo) => (
          <div key={todo._id}>
            <Link href={`/todos/${todo._id}`} passHref>
              <h3 style={{ cursor: "pointer" }}>
                {todo.title} - {todo.completed ? "completed" : "incomplete"}
              </h3>
            </Link>
          </div>
        ))}
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  // get todo data from API
  const res = await fetch(process.env.API_URL as string)
  const todos = await res.json()

  // return props
  return {
    props: { todos },
  }
}

export default Home
